# Generated by Django 4.2 on 2023-06-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_alter_alamatpengiriman_options_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkitem',
            name='kategori',
            field=models.CharField(choices=[('F', 'Fashion'), ('T', 'Toys'), ('S', 'Stuff')], max_length=2),
        ),
        migrations.AlterField(
            model_name='produkitem',
            name='label',
            field=models.CharField(choices=[('New Product', 'primary'), ('SALE', 'info'), ('Best Seller', 'danger')], max_length=20),
        ),
    ]
